// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3qY624UWh6H8MMLrcS4lv1kh8_A3Ba4c',
    appId: '1:164164182612:web:1fa81852dd8b7a23cf43c1',
    messagingSenderId: '164164182612',
    projectId: 'firstfirebaseproject-914c4',
    authDomain: 'firstfirebaseproject-914c4.firebaseapp.com',
    storageBucket: 'firstfirebaseproject-914c4.appspot.com',
    measurementId: 'G-P2Y5CM1D94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABSO7Je052M-mV8h1d2Eu-c4135Se0UDU',
    appId: '1:164164182612:android:afec5d4c0aa11ebecf43c1',
    messagingSenderId: '164164182612',
    projectId: 'firstfirebaseproject-914c4',
    storageBucket: 'firstfirebaseproject-914c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs8mZueZ0VUSDwk4qEtTfp_oQfq3WJYow',
    appId: '1:164164182612:ios:3a9084832e373f1ecf43c1',
    messagingSenderId: '164164182612',
    projectId: 'firstfirebaseproject-914c4',
    storageBucket: 'firstfirebaseproject-914c4.appspot.com',
    iosBundleId: 'com.prabin.firebasefirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs8mZueZ0VUSDwk4qEtTfp_oQfq3WJYow',
    appId: '1:164164182612:ios:3a9084832e373f1ecf43c1',
    messagingSenderId: '164164182612',
    projectId: 'firstfirebaseproject-914c4',
    storageBucket: 'firstfirebaseproject-914c4.appspot.com',
    iosBundleId: 'com.prabin.firebasefirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3qY624UWh6H8MMLrcS4lv1kh8_A3Ba4c',
    appId: '1:164164182612:web:5aa631a35f918493cf43c1',
    messagingSenderId: '164164182612',
    projectId: 'firstfirebaseproject-914c4',
    authDomain: 'firstfirebaseproject-914c4.firebaseapp.com',
    storageBucket: 'firstfirebaseproject-914c4.appspot.com',
    measurementId: 'G-W4RP87137C',
  );
}
